### PR TITLE
Fix tab list for players on 1.7.10, resolves #16

### LINKED ISSUE #16: Fix tab list for 1.7 players
`ViaRewind` allows `1.7` players to join the server as a `1.8` player. The `1.7` tab list is quite different, so we want to disable it, only problem is `PGM` has no way of determining if the player is a `1.8` player or a secret `1.7` player "disguised" as a `1.8` player. ~~Ideally, we do not import any new APIs to do this.~~ Any ideas?

### PR DESCRIPTION
**Pull request by Meeples10**
1.7.10 tab list

### CODE REVIEW

File: src/main/java/tc/oc/pgm/listeners/LongRangeTNTListener.java [hunk 1]
```diff
@@ -271,7 +272,9 @@ private void removeTNT(Entity entity, boolean explode) {
 
   @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
   public void onPlayerJoin(final PlayerJoinEvent event) {
-    this.viewsByPlayer.put(event.getPlayer(), new View(event.getPlayer()));
+    if (ViaUtils.getProtocolVersion(event.getPlayer()) >= 47) {
```
Comment (Pablete1234) [inline src/main/java/tc/oc/pgm/listeners/LongRangeTNTListener.java]: Create a util for protocol versions, `47` means nothing but `Protocol.VERSION_1_7` (or something along those lines) is easy to read

File: src/main/java/tc/oc/tablist/TabRender.java [hunk 2]
```diff
@@ -53,6 +54,9 @@ private BaseComponent getContent(TabEntry entry, int index) {
   }
 
   private void appendAddition(TabEntry entry, int index) {
+    if (ViaUtils.getProtocolVersion(this.view.getViewer()) < 47) {
```
Comment (Pablete1234) [inline src/main/java/tc/oc/tablist/TabRender.java]: This is a complete and absolute hack. Don't change the current tab view to avoid sending packets to 1.7 players, give them a new no-op view

File: src/main/java/tc/oc/tablist/TabRender.java [hunk 3]
```diff
@@ -154,6 +158,9 @@ public void setHeaderFooter(TabEntry header, TabEntry footer) {
   }
 
   public void updateFakeEntity(TabEntry entry, boolean create) {
+    if (ViaUtils.getProtocolVersion(this.view.getViewer()) < 47) {
```
Comment (Pablete1234) [inline src/main/java/tc/oc/tablist/TabRender.java]: See previous comment

File: src/main/java/tc/oc/pgm/PGMImpl.java [hunk 4]
```diff
@@ -143,12 +160,13 @@
...
 import tc.oc.pgm.wool.WoolModule;
 import tc.oc.pgm.worldborder.WorldBorderModule;
+import tc.oc.tablist.TabManager;
 import tc.oc.util.SemanticVersion;
 
 public final class PGMImpl extends JavaPlugin implements PGM {
 
   private MatchManager matchManager;
-  private MatchTabManager matchTabManager;
+  private TabManager tabManager;
```
Comment (Pablete1234) [inline src/main/java/tc/oc/pgm/PGMImpl.java]: I don't get why this was changed (and the subsequent changes) if you aren't even changing the MatchTabManager for 1.7/1.8+ players.

Comment (Meeples10) [reply src/main/java/tc/oc/pgm/PGMImpl.java]: Sorry, I had meant to do something different than what I ended up doing and forgot to undo this.

File: src/main/java/tc/oc/tablist/TabRender.java [hunk 5]
```diff
@@ -53,6 +54,9 @@ private BaseComponent getContent(TabEntry entry, int index) {
   }
 
   private void appendAddition(TabEntry entry, int index) {
+    if (ViaUtils.getProtocolVersion(this.view.getViewer()) < ViaUtils.VERSION_1_8) {
+      return;
+    }
```
Comment (Pablete1234) [inline src/main/java/tc/oc/tablist/TabRender.java]: This check shouldn't be here, instead, this renderer shouldn't be called for 1.7 clients

File: src/main/java/tc/oc/tablist/TabRender.java [hunk 6]
```diff
@@ -154,6 +158,9 @@ public void setHeaderFooter(TabEntry header, TabEntry footer) {
   }
 
   public void updateFakeEntity(TabEntry entry, boolean create) {
+    if (ViaUtils.getProtocolVersion(this.view.getViewer()) < ViaUtils.VERSION_1_8) {
+      return;
+    }
```
Comment (Pablete1234) [inline src/main/java/tc/oc/tablist/TabRender.java]: Same here

File: src/main/java/tc/oc/tablist/TabView.java [hunk 7]
```diff
@@ -365,4 +367,10 @@ protected void onRespawn(PlayerRespawnEvent event) {
   protected void onWorldChange(PlayerChangedWorldEvent event) {
     if (this.viewer == event.getPlayer()) this.respawnFakeEntities();
   }
+
+  public void onViewerJoinMatch(PlayerJoinMatchEvent event) {
```
Comment (Pablete1234) [inline src/main/java/tc/oc/tablist/TabView.java]: May i ask why this is now necessary?

File: src/main/java/tc/oc/tablist/TabView.java [hunk 8]
```diff
@@ -16,7 +18,7 @@
  * bottom and cannot be seen. The fake team names all start with a '\u0001' character, so they will
  * always come before any real teams.
  */
-public class TabView {
+public class TabView implements Listener {
```
Comment (Pablete1234) [inline src/main/java/tc/oc/tablist/TabView.java]: I do not think this is or should be a listener

File: src/main/java/tc/oc/tablist/LegacyTabView.java [hunk 9]
```diff
@@ -0,0 +1,85 @@
...
+
+  public void renderLayout(TabRender render) {}
+
+  public void renderContent(TabRender render) {}
+
+  public void markSlotsClean() {}
+
+  public void renderHeaderFooter(TabRender render, boolean force) {}
+
+  public void onViewerJoinMatch(PlayerJoinMatchEvent event) {}
```
Comment (Pablete1234) [inline src/main/java/tc/oc/tablist/LegacyTabView.java]: I think you only need to override the `render()` method to no-op here, everything else either isn't even used nor overriding (like `onViewerJoinMatch`) or you shouldn't be overriding anyways

File: src/main/java/tc/oc/pgm/tablist/MatchTabManager.java [hunk 10]
```diff
@@ -94,8 +95,8 @@ public void run() {
   @Override
   public @Nullable TabView getView(Player viewer) {
     TabView view = super.getView(viewer);
-    if (view != null && !(view instanceof LegacyMatchTabView)) {
-      this.registerEvents((MatchTabView) view);
+    if (view instanceof ListeningTabView) {
```
Comment (Pablete1234) [inline src/main/java/tc/oc/pgm/tablist/MatchTabManager.java]:
```suggestion
    if (view != null && view instanceof ListeningTabView) {
```

File: src/main/java/tc/oc/pgm/tablist/MatchTabManager.java [hunk 11]
```diff
@@ -151,8 +152,8 @@ public void onMatchUnload(MatchUnloadEvent event) {
   @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
   public void onJoinMatch(PlayerJoinMatchEvent event) {
     TabView view = this.getView(event.getPlayer().getBukkit());
-    if (view != null && !(view instanceof LegacyMatchTabView)) {
-      ((MatchTabView) view).onViewerJoinMatch(event);
+    if (view instanceof ListeningTabView) {
```
Comment (Pablete1234) [inline src/main/java/tc/oc/pgm/tablist/MatchTabManager.java]:
```suggestion
    if (view != null && view instanceof ListeningTabView) {
```

File: src/main/java/tc/oc/pgm/tablist/MatchTabManager.java (hunk 10 above)
Comment (Meeples10) [reply src/main/java/tc/oc/pgm/tablist/MatchTabManager.java]: Is a null check really needed if there is an `instanceof` check? `instanceof` will return false if the object is null.

Comment (Pablete1234) [reply src/main/java/tc/oc/pgm/tablist/MatchTabManager.java]: true, why did it have it before?
