### PR TITLE
Fixed Timed Restarts

### LINKED ISSUE #9: Fix inaccurate /restart countdowns
`RestartManager` schedules a repeatable task to check if the server was queued to restart, then restarts. Instead of a repeatable task, it should queue a delayed task to run at the time it was scheduled restart. If the restart is "deferred" (see code) or cancelled, the task gets canceled.

### PR DESCRIPTION
**Pull request by ThatOneTqnk**
Uses a delayed task and only does its job if there are no deferrals. Task is cancelled if `RestartManager#cancelRestart` is called. Resolves #9 .

Renames `/restart` to `/timedrestart` (Otherwise, it uses the default `/restart` from Spigot)

Signed-off-by: ThatOneTqnk <nodeadbatteries@gmail.com>

### CODE REVIEW

File: src/main/java/tc/oc/pgm/restart/RestartManager.java [hunk 1]
```diff
@@ -35,6 +35,8 @@ public static RestartManager get() {
   private Instant queuedAt;
   private String reason;
 
+  private int timedQueuedRestartTaskID;
```
Comment (Pablete1234) [inline src/main/java/tc/oc/pgm/restart/RestartManager.java]: This needs a better name, probably `queuedRestartTask`?

File: src/main/java/tc/oc/pgm/restart/RestartManager.java [hunk 2]
```diff
@@ -94,6 +96,28 @@ public boolean isRestartDeferredBy(RequestRestartEvent.Deferral deferral) {
     return this.deferrals.contains(deferral);
   }
 
+  public void requestTimedRestart(Duration duration) {
+    Instant queueStamp = Instant.now();
+    long ticks = duration.getStandardSeconds() * 20;
+    timedQueuedRestartTaskID =
+        this.plugin
+            .getServer()
+            .getScheduler()
```
Comment (Pablete1234) [inline src/main/java/tc/oc/pgm/restart/RestartManager.java]: `Bukkit.getScheduler()` would make this more concise

File: src/main/java/tc/oc/pgm/restart/RestartManager.java [hunk 3]
```diff
@@ -94,6 +96,28 @@ public boolean isRestartDeferredBy(RequestRestartEvent.Deferral deferral) {
...
+            .runTaskLater(
+                this.plugin,
+                () -> {
+                  if (!this.deferrals.isEmpty()) {
+                    timedQueuedRestartTaskID = 0;
+                    return;
+                  }
+                  timedQueuedRestartTaskID = 0;
```
Comment (Pablete1234) [inline src/main/java/tc/oc/pgm/restart/RestartManager.java]: If you're going to reset the taskId anyways, just place it once before the conditional

File: src/main/java/tc/oc/pgm/restart/RestartManager.java (hunk 2 above)
Comment (ThatOneTqnk) [reply src/main/java/tc/oc/pgm/restart/RestartManager.java]: only did that to stay consistent with https://github.com/Electroid/PGM/blob/2c5a496911b9d3ca8e77ddbb62415c208a70e3b4/src/main/java/tc/oc/pgm/restart/RestartManager.java#L126-L128

File: src/main/java/tc/oc/pgm/restart/RestartManager.java (hunk 1 above)
Comment (ThatOneTqnk) [reply src/main/java/tc/oc/pgm/restart/RestartManager.java]: renamed

File: src/main/java/tc/oc/pgm/restart/RestartManager.java [hunk 4]
```diff
@@ -94,6 +97,23 @@ public boolean isRestartDeferredBy(RequestRestartEvent.Deferral deferral) {
     return this.deferrals.contains(deferral);
   }
 
+  public void requestTimedRestart(Duration duration) {
```
Comment (Electroid) [inline src/main/java/tc/oc/pgm/restart/RestartManager.java]: What happens if this method was already called? will the previous task get cancelled? Doesn't seem to do that right now.

Comment (ThatOneTqnk) [reply src/main/java/tc/oc/pgm/restart/RestartManager.java]: Ah true, fixed.
